version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./:/app
  php:
    build: ./php
    volumes:
      - ./:/app
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./sql/blog_1.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db

volumes:
  db-data: {}